name: Lint source code

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tool: [flake8, mypy]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run:  pip install -U tox
    - name: Run Tox
      run:  tox -e ${{ matrix.tool }}
