name: Commonmark Spec

on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 * * SUN"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tool: [spec, htmlspec]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run:  pip install -U tox
    - name: Run Tox
      run:  tox -e ${{ matrix.tool }}
